data:
  dataset_path: '~/data/nlp/classification/THUCNews/'
  processed_path: '~/data/processed-data/classification/textcnn'
  train_data: 'train-files.txt'
  test_data: 'test-files.txt'

  vocab_file: 'vocab.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

  max_sequence_length: 1000

model:
  embedding_size: 100
  num_filters: 100
  kernel_sizes: [3, 4, 5]
  dropout_keep_prob: 0.5
  fc_unit: 14

train:
  batch_size: 50

  max_gradient_norm: 3.0

  learning_rate: 0.001
  learning_decay_rate: 0.8

  epoch: 0
  max_epoch: 10
  model_dir: '~/data/logs/nlp/classification/textcnn'

  save_checkpoints_steps: 2000

