data:
  dataset_path: 'D:/data/dataset/structured-prediction/'
  processed_path: 'D:/data/processed-data/structured-prediction/'

  train_data: 'train.conll'
  test_data: 'test.conll'

  num_stack_word: 3
  children_stack_range: 2

  vocab_file: 'vocab.txt'
  pos_file: 'pos.txt'
  dep_file: 'dep.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  word_feature_num: 18
  pos_feature_num: 18
  dep_feature_num: 12
  fc_unit: 200
  reg_scale: 0.00000001
  dropout_keep_prob: 0.5
  dep_num: 47
  pos_num: 39
  beam_size: 100
  word_embedding_size: 300
  pos_embedding_size: 100
  dep_embedding_size: 100

train:
  batch_size: 10
  initial_lr: 0.001

  epoch: 0
  max_epoch: 15

  model_dir: 'D:/data/logs/structured-prediction/'
  save_checkpoints_steps: 2000