data:
  dataset_path: '~/big_data/dataset/nlp/dependency-parsing/'
  processed_path: '~/big_data/processed-data/nlp/dependency-parsing/stack-lstm+swap/'

  train_data: 'train.conll'
  test_data: 'test.conll'

  num_stack_word: 3
  children_stack_range: 2

  vocab_file: 'vocab.txt'
  pos_file: 'pos.txt'
  dep_file: 'dep.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  lstm_unit: 100
  lstm_layer_num: 2
  embedding_fc_unit: 100
  fc_unit: 200
  reg_scale: 0.00000001
  dropout_keep_prob: 0.5

  dep_num: 46
  pos_num: 38

  word_embedding_size: 300
  pos_embedding_size: 30
  history_action_embedding_size: 30
  comp_action_embedding_size: 30

train:
  batch_size: 5
  initial_lr: 0.01
  reg_scale: 0.00000001

  epoch: 0
  max_epoch: 15

  model_dir: '~/big_data/logs/nlp/dependency-parsing/stack-lstm+swap/'
  save_checkpoints_steps: 2000