data:
  dataset_path: '~/big_data/dataset/nlp/dependency-parsing/'
  processed_path: '~/big_data/processed-data/nlp/dependency-parsing/stack-lstm+swap/'

  train_data: 'train.conll'
  test_data: 'test.conll'

  vocab_file: 'vocab.txt'
  pos_file: 'pos.txt'
  dep_file: 'dep.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  lstm_unit: 100
  lstm_layer_num: 2
  embedding_fc_unit: 50

  dep_num: 46
  pos_num: 38

  word_embedding_size: 300
  pos_embedding_size: 20
  history_action_embedding_size: 20
  comp_action_embedding_size: 20

train:
  batch_size: 32
  initial_lr: 0.1
  lr_decay: 0.1
  reg_scale: 0.000001

  max_gradient_norm: 5.0

  epoch: 0
  max_epoch: 10

  model_dir: '~/big_data/logs/nlp/dependency-parsing/stack-lstm+swap/'

  save_checkpoints_steps: 2000