data:
  dataset_path: '~/data/dataset/nlp/ner/'
  processed_path: '~/data/processed-data/nlp/ner/bilism-crf/origin'

  train_data: 'train.txt'
  test_data: 'test.txt'

  vocab_file: 'vocab.txt'
  tag_file: 'tag.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  lstm_unit: 100
  fc_unit: 13
  dropout_keep_prob: 0.5
  embedding_size: 100

train:
  batch_size: 20
  max_gradient_norm: 5.0

  initial_lr: 0.01

  epoch: 0
  max_epoch: 10

  model_dir: '~/data/logs/nlp/ner/bilism-crf/origin'
  save_checkpoints_steps: 2000