data:
  dataset_path: '~/data/dataset/nlp/ner/'
  processed_path: '~/data/processed-data/nlp/ner/bilstm-crf/'

  train_data: 'train.txt'
  test_data: 'test.txt'

  vocab_file: 'vocab.txt'
  tag_file: 'tag.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  class_num: 12
  tag_num:

  dropout_keep_prob: 0.5
  word_embedding_size: 100
  tag_embedding_size: 50
  position_embedding_size: 5

train:
  batch_size: 20
  max_gradient_norm: 5.0

  initial_lr: 0.01

  epoch: 0
  max_epoch: 15

  model_dir: '~/data/logs/nlp/ner/bilstm-crf/'
  save_checkpoints_steps: 2000