data:
  dataset_path: '~/data/dataset/nlp/classification/THUCNews/'
  processed_path: '~/data/processed-data/nlp/classification/dpcnn'
  train_data: 'train-files.txt'
  test_data: 'test-files.txt'

  vocab_file: 'vocab.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

  max_sequence_length: 1000

model:
  kernel_sizes: [1, 3, 5]
  fixed_channel: 250
  fc_unit: 14
  embedding_size: 100
  max_conv_block_num: 3

train:
  batch_size: 100

  regular_weight: 0.0001
  dropout_keep_prob: 0.5

  learning_rate: 0.01

  epoch: 0
  max_epoch: 10
  model_dir: '~/data/logs/nlp/classification/dpcnn/conv-block-3'

  save_checkpoints_steps: 2000
