data:
  dataset_path: '~/data/dataset/nlp/classification/THUCNews/'
  processed_path: '~/big_data/processed-data/nlp/language-model/elmo/'

  train_data: 'train-files.txt'
  test_data: 'test-files.txt'

  vocab_file: 'vocab.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

  char_pkl: 'char.pkl'

model:
  char_image_size: 32
  highway_layer_num: 2
  lstm_layer_num: 2
  lstm_unit: 2048
  fc_unit: 21
  dropout_keep_prob: 0.9
  embedding_size: 300
  lstm_cell_clip: 3.0
  lstm_proj_clip: 3.0
  seq_length: 30
  vocab_num: 7425

train:
  batch_size: 20
  max_gradient_norm: 5.0
  sampled_num: 3000
  initial_lr: 0.2

  epoch: 0
  max_epoch: 10

  model_dir: '~/big_data/logs/nlp/language-model/elmo/'
  save_checkpoints_steps: 2000