data:
  base_path: 'data/'
  raw_path: 'raw_data/'
  processed_path: 'processed_data'
  wordvec_fname: 'glove.txt'
  tag_labels: ['身体部位', '治疗', '症状和体征', '检查和检验', '疾病和诊断']

model:
  lstm_unit: 200
  fc_unit: 100
  num_class: 79

  dropout_keep_prob: 0.5
  embedding_size: 64

train:
  batch_size: 16
  max_gradient_norm: 5.0
  learning_rate: 0.001
  learning_decay_steps: 500
  learning_decay_rate: 0.8
  optimizer: 'Adam'
  max_steps: 5000
  model_dir: 'logs/NER/bilstm-crf/'

  save_checkpoints_steps: 500
  check_hook_n_iter: 100

  debug: False