data:
  dataset_path: '~/big_data/dataset/nlp/natural-language-inference/'
  processed_path: '~/big_data/processed-data/nlp/natural-language-inference/diin/'

  train_data: 'train.txt'
  test_data: 'test.txt'

  vocab_file: 'vocab.txt'
  pos_file: 'pos.txt'
  wordvec_file: 'wordvec.txt'
  wordvec_pkl: 'wordvec.pkl'

model:
  max_seq_length: 50
  char_image_size: 32
  max_char: 6
  feature_scale_ratio: 0.3
  dense_transition_ratio: 0.5
  cnn_dense_units: 100
  highway_num: 2
  dense_block_num: 3
  dense_layer_per_block: 3

  pos_num: 29

  word_embedding_size: 300
  pos_embedding_size: 50

train:
  batch_size: 1
  switch_optimizer: 0
  initial_lr: 0.5
  sgd_lr: 0.004
  l2_full_ratio: 0.0001
  constraint_scale: 0.001
  dropout_decay: 0.95
  epoch: 0
  max_epoch: 15

  model_dir: '~/big_data/logs/nlp/natural-language-inference/diin/'
  save_checkpoints_steps: 2000