data:
  base_path: 'data/'
  num_stack_word: 3
  children_stack_range: 2
  wordvec_file: 'word_emb.pkl'
  posvec_file: 'pos_emb.pkl'
  depvec_file: 'dep_emb.pkl'
  num_dep: 39

model:
  fc1_unit: 200
  reg_scale: 0.00000001
  dropout_keep_prob: 0.5

train:
  batch_size: 2048
  learning_rate: 0.001
  optimizer: 'Adam'

  epoch: 10
  model_dir: 'logs/MLP-Parser'

  save_checkpoints_steps: 1000
  check_hook_n_iter: 100

  debug: False