data:
  base_path: 'data/'
  raw_data: 'people1998.txt'
  wordvec_fname: 'glove.txt'

model:
  gru_unit: 200
  fc_unit: 176
  dropout_keep_prob: 0.5
  embedding_size: 64

train:
  batch_size: 16
  max_gradient_norm: 5.0
  learning_rate: 0.001
  learning_decay_steps: 500
  learning_decay_rate: 0.9
  optimizer: 'Adam'
  max_steps: 20000
  model_dir: 'logs/seg_tag/birnn-crf/'

  save_checkpoints_steps: 700
  check_hook_n_iter: 100

  debug: False